// --------------------------------------------------------
// Code generated by Papyrus Java

// --------------------------------------------------------

package Tema_ISP;

import java.util.ArrayList;

import java.util.HashMap;

public class Grupa {

	private String nume;
	private String serie;
	private String user;
	private String parola;
	private boolean logat = false;
	private ArrayList<String> listaMaterii = new ArrayList<String>();
	private boolean dispobilitate = true;

	public boolean isDispobilitate() {
		return dispobilitate;
	}

	public Grupa(String nume, String serie) {
		super();
		this.nume = nume;
		this.serie = serie;
	}

	public void setDispobilitate(boolean dispobilitate) {
		this.dispobilitate = dispobilitate;
	}

	public void afisareStudent() {
		System.out.println("Student: " + nume);
	}

	public String getNume() {
		return nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public void logare(String nume, String parola) {
		HashMap<String, String> hm = Aplicatie.getConturi();
		if (!logat && hm.get(this.parola) != null) {
			System.out.println("Buna, " + nume);
			logat = true;
		} else if (logat)
			System.out.println("Sunteti deja logat");
		else
			System.out.println("Nu aveti cont");
	}

	public void delogare() {
		if (logat) {
			System.out.println("La revedere, " + nume);
			logat = false;
		} else
			System.out.println("Nu sunteti inca logat");
	}

	public ArrayList<CelulaOrar> vizualizareOrarZilnic(String zi) {
		ArrayList<CelulaOrar> orarZiGrupa = new ArrayList<CelulaOrar>();
		if (zi.equals("Luni") || zi.equals("Marti") || zi.equals("Miercuri") || zi.equals("Joi")
				|| zi.equals("Vineri")) {
			for (CelulaOrar celula : Secretar.celuleOrar)
				if (celula.getSala().getZi().equals(zi) && celula.getMaterie().getGrupa() == this)
					orarZiGrupa.add(celula);
		} else
			System.out.println("Zi invalida");
		return orarZiGrupa;
	}

	public ArrayList<CelulaOrar> vizualizareOrarSaptamana() {
		ArrayList<CelulaOrar> orarGrupa = new ArrayList<CelulaOrar>();
		for (CelulaOrar celula : Secretar.celuleOrar)
			if (celula.getMaterie().getGrupa() == this)
				orarGrupa.add(celula);
		return orarGrupa;
	}

	public void adaugareMaterie(String materie) {
		this.listaMaterii.add(materie);
	}

	public void stergereMaterie(Materie materie) {
		if (listaMaterii.contains(materie))
			listaMaterii.remove(materie);
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getParola() {
		return parola;
	}

	public void setParola(String parola) {
		this.parola = parola;
	}

	public String getSerie() {
		return serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	public ArrayList<String> getListaMaterii() {
		return listaMaterii;
	}

	public void setListaMaterii(ArrayList<String> listaMaterii) {
		this.listaMaterii = listaMaterii;
	}

};
