// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema_ISP;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.HashMap;

import Tema_ISP.Materie;

public class Profesor {

	private String nume;
	private String user;
	private String parola;
	private boolean logat;
	private ArrayList<String> materii = new ArrayList<String>();
	private boolean disponibilitate = true;
	InputStreamReader isr = new InputStreamReader(System.in);
	BufferedReader br = new BufferedReader(isr);

	public void afisareProfesor() {
		System.out.println("Profesor: " + this.nume);
	}

	
	public ArrayList<String> getMaterii() {
		return materii;
	}


	public void logareProfesor() {
		HashMap<String, String> hm = Aplicatie.getConturi();
		if (!logat && hm.get(this.parola) != null) {
			System.out.println("Buna, " + nume);
			logat = true;
		} else if (logat)
			System.out.println("Sunteti deja logat");
		else
			System.out.println("Nu aveti cont");
	}

	public void delogareProfesor() {
		if (logat) {
			System.out.println("La revedere, " + nume);
			logat = false;
		} else
			System.out.println("Nu sunteti inca logat");
	}

	public void modificareParolaProfesor() throws IOException {
		System.out.println("Username: ");
		String u = br.readLine();
		if (u.equals(this.user)) {
			System.out.println("Noua parola: ");
			String pn = br.readLine();
			this.parola = pn;
		} else
			System.out.println("Username invalid");
	}

	public void vizualizareOrarMaterieProfesor(String materie) {
	}

	public void vizualizareOrarZi(String zi) {
	}

	public void vizualizareOrarProfesor() {
	}

	public void adaugareMaterie(String materie) {
		this.materii.add(materie);
	}

	public void stergereMaterie(String materie) {
		if (materii.contains(materie))
			materii.remove(materie);
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getParola() {
		return parola;
	}

	public void setParola(String parola) {
		this.parola = parola;
	}

	public String getNume() {
		return nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public boolean isDisponibilitate() {
		return disponibilitate;
	}

	public void setDisponibilitate(boolean disponibilitate) {
		this.disponibilitate = disponibilitate;
	}
	
};
